spring.application.name=springboot-jpa

spring.datasource.url=jdbc:mysql:///spring_learning_jdbc
spring.datasource.username=root
spring.datasource.password=Lovealarm@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true